### ISSUE TITLE
Reason it was deprecated?

### ISSUE THREAD

**Issue by Hevia** [nuxlar/MoreElites#1]
Any reason this mod was deprecated? The Elites added sound cool

I'm happy to fork & maintain it with your permission. There are so few good Elite mods that don't come bundled with other stuff would love to see this brought back.

**Comment by nuxlar** [comment]
ye i deprecated it cuz i wanted to fix some things and make the elites more interesting but got caught up in other things. so it might be coming back soon ive just been busy with other mods

**Comment by Hevia** [comment]
Thanks for the update. Will close
