### ISSUE TITLE
Frenzied and Wake of Vultures

### ISSUE THREAD

**Issue by Moffein** [Nuxlar/MoreElites#1]
Noticed that when getting the Frenzied affix via Wake of Vultures, it teleports you randomly and can get you killed.
Would be nice if there was a isPlayerControlled check behind it.

**Comment by Nuxlar** [comment]
sorry I just saw this, yeah there's a lot of polishing up I need to do with the frenzied elites

**Comment by Nuxlar** [comment]
done!
